name: mentalhealthapp
description: A mental health application with Gen Z style login and home page.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_login: ^4.2.1
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  confetti: ^0.7.0
  badges: ^3.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.0  
  timeago: ^3.3.0
  flutter_slidable: ^3.0.0  
  flutter_animate: ^4.2.0
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.4.0 

  # Other dependencies can go here
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/exercise.json
    - assets/emptybox.json
    - assets/profileanimation.json
    - assets/profileanimate.json
    - assets/profileanimate1.json
    - assets/profileanimate2.json
    - assets/profileanimate3.json
    - assets/profileanimate.json
    - assets/loginanimation.json
    - pict/fin.webp
